# SuperVanish v5.5.0 - Configuration
#
Configuration:
##################################################
################ MESSAGE OPTIONS #################
##################################################
  Messages:
    ####### Fake Join-/LeaveMessages #######
    VanishReappearMessages:
      # Should this plugin broadcast a message when a player vanishs?
      # You can change that message in the messages.yml file.
      BroadcastMessageOnVanish: true
      # Should this plugin broadcast a message when a player reappears?
      # You can change that message in the messages.yml file.
      BroadcastMessageOnReappear: true
      # Should players with the permission 'sv.see' get an other message when a player vanishs/reappears?
      # You can change that message in the messages.yml file.
      SendDifferentMessages: true
      # Should only players with the permission 'sv.see' receive 'fake' Join-/LeaveMessages?
      SendMessageOnlyToAdmins: false
      # Should only players without the permission 'sv.see' receive 'fake' Join-/LeaveMessages?
      SendMessageOnlyToUsers: false
    ########################################
    # Should this plugin hide the 'normal' Join- and LeaveMessages of invisible players?
    HideNormalJoinAndLeaveMessagesWhileInvisible: true
    # Should this plugin remember players who join the server invisible?
    # You can change that message in the messages.yml file.
    RememberInvisiblePlayersOnJoin: true
    # Should this plugin use BarAPI to show invisible players awesome bossbars?
    # Requires BarAPI.
    # You can change the bars in the messages.yml file.
    UseBarAPI: false
    # Should invisible players have action bars that tell them that they're invisible?
    # You can change the actionbar msg in the messages.yml file.
    DisplayActionBarsToInvisiblePlayers: true
##################################################
################ PLAYER OPTIONS ##################
##################################################
  Players:
    # Should invisible players be able to pick up items?
    DisableItemPickUpsByDefault: true
    # Should players with the permission 'sv.see' view invisible players as ghosts?
    # This feature uses scoreboard teams and could break other plugins.
    # Please disable this feature if it causes problems.
    EnableGhostPlayers: false
    # Should invisible players have the night vision effect?
    AddNightVision: true
    # Should this plugin disable hunger of invisible players?
    DisableHungerForInvisiblePlayers: true
    ################## FLY #################
    Fly:
      # Should invisible players be able to fly even if they aren't in creative mode?
      Enable: true
      # Should invisible players WITHOUT the permission 'sv.fly' lose the ability to fly on reappear?
      DisableOnReappear: true
    ########################################
    # Should invisible players not be able to trigger pressure plates and tripwire?
    # If this feature is enabled invisible players can't trigger pressure plates and tripwire.
    DisablePressurePlatesForInvisiblePlayers: true
    # Should players with the permission 'sv.see' be able to see invisible players?
    EnableSeePermission: true
    # Should invisible players not be able to break blocks?
    PreventBlockBreaking: false
    # Should invisible players not be able to place blocks?
    PreventBlockPlacing: false
    # Should invisible players not be able to damage players or mobs?
    PreventHittingEntities: false
    # Should invisible players open chests without the chest animation and sounds? Requires ProtocolLib.
    SilentOpenChest: true
    # Should invisible players automatically reappear when they change their world?
    ReappearOnWorldChange: false
    # Should invisible players automatically reappear when they quit the server?
    ReappearOnQuit: false
    # Should SV still handle leave messages if 'ReappearOnQuit' is turned on?
    ReappearOnQuitHandleLeaveMsg: true
##################################################
################ TABLIST OPTIONS #################
##################################################
  Tablist:
    # Should this plugin change the tabname of invisible players?
    # Players without the permission 'sv.see' won't see this tabname.
    # This feature changes the tabname of invisible players and could break other plugins.
    # You can change the new tabname in the messages.yml file.
    # Please note that tabnames can only have a length of 16 or less characters.
    ChangeTabNames: true
##################################################
############## SERVERLIST OPTIONS ################
##################################################
  Serverlist:
    # !! PLEASE TURN THE NEXT TWO SETTINGS OFF IF YOU ARE RUNNING BUNGEECORD !!
    # The ServerList-features require the plugin ProtocolLib and don't support BungeeCord!
    # Should this plugin adjust the amount of players in the serverlist?
    AdjustAmountOfOnlinePlayers: true
    # Should this plugin hide invisible players in the list of logged in players?
    # You can view this list when your mouse hovers over the amount of online players.
    AdjustListOfLoggedInPlayers: true
##################################################
################## HOOK OPTIONS ##################
##################################################
  Hooks:
    # Should SV hide invisible players in /who, /list, /online
    # and all other commands of Essentials?
    # Note: Players with a specific essentials-permission can still see invisible players in those commands
    # Important: You have to reload both Essentials and SuperVanish if you change this setting.
    EnableEssentialsHook: true
    # Should SV hide invisible players on your dynamic map and broadcast join/leave messages if you use Dynmap?
    EnableDynmapHook: true
    # Should SV prevent players from being invisible and disguised at the same time? (LibsDisguises commands)
    # It's recommended to keep this turned on to prevent incompatibility.
    EnableLibsDisguisesHook: true
    # Should SV prevent players from being invisible and disguised at the same time? (DisguiseCraft commands)
    # It's recommended to keep this turned on to prevent incompatibility.
    EnableDisguiseCraftHook: true
    # Should SV hook into TraiGUI and disable trails for vanished players?
    EnableTrailGUIHook: true
    # Should SV hook into SuperTrails and disable trails for vanished players?
    EnableSuperTrailsHook: true
##################################################
############# COMPATIBILITY OPTIONS ##############
##################################################
  CompatibilityOptions:
    # 1 second is equal to 20 ticks
    # Positive integers only.
    ActionDelay:
      # The settings below won't do anything if this is 'false'.
      Enable: false
      TabNameChangeDelayOnJoinInTicks: 5
      TabNameChangeDelayOnWorldChangeInTicks: 5
      # If 'EnableGhostPlayers' is enabled
      InvisibilityPotionDelayOnJoinInTicks: 3
      InvisibilityPotionDelayOnWorldChangeInTicks: 3
    # The event-priority supervanish should use for the specific event.
    # If another plugin overrides supervanish's join/leave settings, setting the priorities to MONITOR can help.
    # Allowed values are: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
    PlayerJoinEventPriority: HIGH # <- Set this to "HIGH" if you use Essentials to modify join messages
    PlayerQuitEventPriority: HIGHEST
#################################################
################# DO NOT TOUCH ##################
#################################################
ConfigVersion: 5.5.0